### ISSUE TITLE
Calling .AsStream() on a pipe that is an IPC stream adds another adapter

### ISSUE THREAD

**Issue by RyanToth3** [AArnott/Nerdbank.Streams#111]
In the case where a Pipe is actually an IPC Stream, the fact that we see it as a Pipe already suggests that there's a stream-to-pipe adapter on it. Sticking on another adapter means we're handing back a stream->pipe->stream object. The underlying stream should be unwrapped when the pipe is just an adapter to just return the original stream instead of stacking adapters.

**Comment by AArnott** [comment]
I can't unwrap a Pipe to be a stream because in the meantime the Pipe has eagerly started reading from the stream. Unwrapping the stream would abandon the bytes that the pipe already read.
But I did enable unwrapping a stream that was covering up a pipe.
