### ISSUE TITLE
Where can we find a getting started reference

### ISSUE THREAD

**Issue by TaviTruman** [AArnott/Nerdbank.Streams#128]
@AArnott Other than the unit testing have you had a chance to generating a getting started developers guide or code reference? Ive got time and space to generate artifacts as I learn the api for sample, example sources.

**Comment by AArnott** [comment]
Thanks for offering. I'd welcome your help to build up more docs. Have you seen the ones linked from the repo's README?

**Comment by TaviTruman** [comment]
@AArnott Yes, I've seen those docs and that content is more than sufficient to build more than just useful code snippets and small programming. What I've learned from a few other repros is that devs require more context and fuller examples. I'll get started on things like console apps and desktop (MVVM) apps and present PR when I get roll-in.

**Comment by AArnott** [comment]
Thanks.

**Comment by TaviTruman** [comment]
Thank you - happy to serve and give back 😊

**Comment by TaviTruman** [comment]
@AArnott Hey, Aaron I was I'm looking to create a directory named "Samples" to store projects that further demonstrate and document the API; looking at some of the other Repro you've authored so you have any preferences w.r.t physical organization and structure setup?

**Comment by AArnott** [comment]
Sure, thanks for asking. I guess a top-level `samples` folder would be preferable based on [a recent discussion](https://github.com/AArnott/Library.Template/issues/26). There should *not* be a separate sln file for the samples though. Please add all the sample projects to the original sln file, under a samples solution folder.

**Comment by TaviTruman** [comment]
That sounds good to me.

**Comment by TaviTruman** [comment]
@AArnott I am starting to build samples. I'm going to use the following use-cases and technology stacks:

- Contact Data Management
- Real Estate Property Management, MLS property data search
- RDF Triple and Semantic App Dev

I'm going to provide .NET Core 3.0 Console and WPF/UWP (.NET Core 3.0) apps. I'm also using WPF PRISM, ReactiveProperty, GraphEngine, and JSON-RPC open source packages.

**Comment by AArnott** [comment]
Wow. That sounds like the samples will be pretty significant. I'm concerned that the points needed to learn about how to use Nerdbank.Streams might get lost amidst the sheer size of the samples. Is that a valid concern for what you're planning?

Which JSON-RPC package are you planning to use? I'm partial to StreamJsonRpc (since I wrote much of it) and it uses Nerdbank.Streams, actually.

**Comment by TaviTruman** [comment]
I'm using StreamJsonRpc :-). I'm trimming the samples down from actual apps I've been working on over the past year. I'm going to provide a goodly amount of documentation calling out the use of Nerdbank.Streams and StreamJsonRpc. I think the documentation you provided is great for most experienced developers but a lot of devs are also intimidated and need a bit more guidance - this has been my experience in trying to build devs teams and hire folks. The samples aren't too big - each one takes a few days to code in my schedule and workload.

**Comment by AArnott** [comment]
Any update on this, or should I close the issue?

**Comment by AArnott** [comment]
We can re-open if needed when you've got something.
