### ISSUE TITLE
Your half-duplex is called simplex

### ISSUE THREAD

**Issue by fubar-coder** [AArnott/Nerdbank.Streams#144]
Half duplex usually means that both sides can send and receive - but not concurrently.

**Comment by AArnott** [comment]
Wow. Thank you for educating me on that. I see you're right. After some quick reading:

(full) duplex: both directions concurrently
half duplex: both directions, but not concurrently
simplex: one direction

I've got a lot to fix. And I'm afraid in this repo some of this is burned into public API names and would be disruptive to fix so I should just comment liberally on those APIs to say what it *really* is.
