### ISSUE TITLE
Question: How best to go about learning to create Azue pipeline and build processes

### ISSUE THREAD

**Issue by TaviTruman** [AArnott/Nerdbank.Streams#150]
@AArnott I've been studying how you've setup azure pipeline and the overall build process for this project and it is elegant, and most importantly, necessary for repeatability, determinate high quality and availability. I was just wondering how does one go about learning to do it all; any suggestions on where to start? I've grown so dependent on VS builds and legacy deployment and Installer, but now I'm moving everything to azure pipelines and Azure App Center for WPF and other native apps via Xamarin. I'm also working on the Desktop samples for Nerdbank.Streams and wanted increase my domain knowledge around the build process.

**Comment by AArnott** [comment]
The Azure Pipelines documentation on docs.microsoft.com are quite good, IMO. I learned much of what I do from that, and simply from owning or influencing dozens of repos so I've seen a lot of what works and doesn't. 

I've tried to encapsulate all the "good" practices in https://github.com/aarnott/library.template. So if you want to see a repo that is nothing but pure best practices for any .NET library repo, I suggest you look there.
