### ISSUE TITLE
Stream.UseStringPipeReader() should throw from ReadAsync and TryRead if AdvanceTo isn't called since last call

### ISSUE THREAD

**Issue by Alxandr** [AArnott/Nerdbank.Streams#153]
The following fails:

```csharp
using var ms = new MemoryStream();
var reader = ms.UseStrictPipeReader();
await reader.ReadAsync();
Assert.True(reader.TryRead(out var _));
```

I would expect `TryRead` to return an empty completed `ReadResult` here, but I might be misunderstanding the API. Do you know what the spec for `PipeReader` says here?

**Comment by AArnott** [comment]
What do you mean by "fails"? Does it throw? It should.

After every read operation from a pipe reader, you must call `PipeReader.AdvanceTo` so it knows how much you consumed from the `ReadResult`.

I'll optimistically close, but comment again if this doesn't resolve your issue.

**Comment by Alxandr** [comment]
`Assert.True` throws cause `TryRead` returns false. As far as my understanding, if you call `ReadAsync` (or in this case `TryRead`) again without having consumed anything, you get the same result back, right? The issue here is that `reader.TryRead` returns false if the stream is empty.

**Comment by AArnott** [comment]
No, the bug is that TryRead doesn't itself throw the second time. The .NET version of PipeReader would have. I'm adding tests now to verify this and fix the bug. You don't have to be blocked by it though: just *always* call `PipeReader.AdvanceTo` after every single read operation.

**Comment by Alxandr** [comment]
Are you sure about that? That sounds like weird API design. The reason I ran into this was code like the following:

```csharp
// fast-path, not using async.
ValueTask<string> ReadAsync(PipeReader reader, CancellationToken cancellationToken)
{
  if (!reader.TryRead(out var result))
    return FetchAndReadAsync(reader, cancellationToken);

  if (!EnoughData(result.Buffer))
  {
    if (result.IsComplete) throw Exception("bad stream");
    return FetchAndReadAsync(reader, cancellationToken);
  }

  return Parse(result.Buffer);
}

// async fetch path
async ValueTask<string> FetchAndReadAsync(PipeReader reader, CancellationToken cancellationToken)
{
  await reader.ReadAsync(cancellationToken).ConfigureAwait(false);
  return await ReadAsync(reader, cancellationToken).ConfigureAwait(false);
}
```

**Comment by Alxandr** [comment]
Seems you're absolutely right ofcause: https://github.com/dotnet/runtime/blob/master/src/libraries/System.IO.Pipelines/tests/PipeReaderWriterFacts.cs#L651

I solved it by passing a nullable `ReadResult` from the fetch method into the read method, but I would have preferred not having to.
