### ISSUE TITLE
SubstreamReader fails when underlying stream returns only part of 4 byte header

### ISSUE THREAD

**Issue by leeview** [AArnott/Nerdbank.Streams#165]
In src/Nerdbank.Streams/SubstreamReader.cs at line 106 there is a subtle bug there:

int bytesJustRead = this.underlyingStream.Read(this.intBuffer, **0**, 4 - bytesRead);

should be

int bytesJustRead = this.underlyingStream.Read(this.intBuffer, **bytesRead**, 4 - bytesRead);

**Comment by AArnott** [comment]
Thanks for the report!

**Comment by AArnott** [comment]
The fix is shipped in 2.4.59
