### ISSUE TITLE
Support System.Net.Sockets.Socket

### ISSUE THREAD

**Issue by bboyle1234** [AArnott/Nerdbank.Streams#177]
Hi, I'm wondering why System.Net.WebSockets.WebSocket is supported but good old System.Net.Sockets.Socket is not supported. (Because I use the old Socket very often and would like to have it supported by this library)

**Comment by AArnott** [comment]
So to be clear, the API you're missing is adapting `Socket` to look like an `IDuplexPipe`, is that it?

**Comment by bboyle1234** [comment]
Yes. By the way, just for fun, I'd like to attempt a PR for it if you think the feature is worthwhile.

**Comment by bboyle1234** [comment]
I'm aware that it can already be done in a one-liner: `new NetworkStream(socket).UsePipe()`, but I'm thinking that probably adds a layer of ineffiency to the system. Correct me if I'm wrong.

**Comment by AArnott** [comment]
I don't usually go to the trouble of removing a layer unless there's pretty good evidence that it will significantly reduce overhead. But the networkstream class is not particularly discoverable if I was just looking at the socket class, so if you would like to submit a PR that adds extension methods that basically apply the adapter that already exists I would accept that.

**Comment by bboyle1234** [comment]
Hi Andrew, after thinking about our conversation, I'm not feeling inclined to add the api, as I feel it's probably best left as a comment in the documentation to the effect of: 

"To use the stream api on System.Net.Sockets.Socket, use new NetworkSocket(socket)"
"To use the pipes api on System.Net.Sockets.Socket, use new NetworkSocket(socket).UsePipes()"

So that's where I would leave it (a comment in the docs) if this were my project.

**Comment by AArnott** [comment]
That's not a bad comment, if you'd like to send a PR to update the docs.
I'll close this issue in the meantime.
