### ISSUE TITLE
Add `Stream ReadOnlySequence<byte>.AsStream()` extension method

### ISSUE THREAD

**Issue by AArnott** [AArnott/Nerdbank.Streams#21]
We should make it super easy to consume a `ReadOnlySequence<byte>` for all the APIs that can read from `Stream`.

See also: https://github.com/dotnet/corefx/issues/31804

**Comment by xChernobyl** [comment]
Yes, I'm currently experiencing big trouble with this - have to do stuff like 
`buffer.Slice(buffer.Start, sizeof(Byte)).ToArray()[0];`

omg :). Please, do something about it.

**Comment by AArnott** [comment]
I'm not sure what you're asking for, @xChernobyl. This issue is closed and the feature was complete. It's in the latest Nerdbank.Streams package on nuget.org
