### ISSUE TITLE
SimplexStream example in documentation does not run

### ISSUE THREAD

**Issue by DaEkstrim** [AArnott/Nerdbank.Streams#259]
I'm trying out this package for unidirectional multithreaded read and write from a stream, and I came across the SimplexStream as specified in the documentation. I copy and pasted the code as is (renamed the `HalfDuplexStream `to `SimplexStream`) in the `private static async Main(string[] args)` entry method and ran the code.

The only output was `...and we're done!`

I then downloaded the source code for the SimplexStream and placed it in the project and the line  `ReadResult readResult = await this.pipe.Reader.ReadAsync(cancellationToken).ConfigureAwait(false);` in method `public override async Task<int> ReadAsync(byte[] buffer, int offset, int count, CancellationToken cancellationToken)` never returns. I can see the writes completing successfully.

Framework: .NetCore 3.1
OS: Windows 10 x64

Let me know if you need any more information.

This is the complete code of Program.cs
```
using Nerdbank.Streams;
using System;
using System.IO;
using System.Threading.Tasks;

namespace SimplexStreamTest
{
    internal class Program
    {
        private static async Task Main(string[] args)
        {
            var stream = new SimplexStream();
            var writer = new StreamWriter(stream);
            var reader = new StreamReader(stream);

            var speaker = Task.Run(async delegate
            {
                await writer.WriteLineAsync("Hello, listener 1!");
                await writer.WriteLineAsync("Hello, listener 2!");
                stream.CompleteWriting();
            });

            var listener = Task.Run(async delegate
            {
                string line;
                while ((line = await reader.ReadLineAsync()) != null)
                {
                    Console.WriteLine("I received: " + line);
                }
            });

            await Task.WhenAll(speaker, listener);
            Console.WriteLine("...and we're done!");
        }
    }
}
```

And this is the console output when run
![image](https://user-images.githubusercontent.com/18722053/95595965-153cd580-0a4d-11eb-9a83-58a1130c1850.png)

**Comment by DaEkstrim** [comment]
I took a look at the closed issues and I came across this one: https://github.com/AArnott/Nerdbank.Streams/issues/186. So I modified the speaker to flush after writing;

```
            var speaker = Task.Run(async delegate
            {
                await writer.WriteLineAsync("Hello, listener 1!");
                await writer.WriteLineAsync("Hello, listener 2!");
                await writer.FlushAsync();
                stream.CompleteWriting();
            });
```

and with that change, it worked. So this is a matter of just updating the documentation.

**Comment by AArnott** [comment]
Where did you get the docs/sample that you say are defective? I can't find the string `...and we're done!` anywhere in the repo.

**Comment by DaEkstrim** [comment]
I got it from the SimplexStream example from the README.md on the front page of the repository: https://github.com/AArnott/Nerdbank.Streams/blob/master/doc/SimplexStream.md

**Comment by AArnott** [comment]
Ah, I somehow missed that in my search. Thank you! I see several stale bits to this page, so I'm updating that as well as the Flush tip you shared. Thank you.
