### ISSUE TITLE
SPAN_BUILTIN constant is not applied for target framework netcoreapp3.1

### ISSUE THREAD

**Issue by tedvanderveen** [AArnott/Nerdbank.Streams#264]
Please compare..
https://github.com/AArnott/Nerdbank.Streams/blob/227ee889fe070bbf1ffcf57d9842887f7bdc3570/src/Nerdbank.Streams/Nerdbank.Streams.csproj#L9

..with this:
https://github.com/AArnott/Nerdbank.Streams/blob/227ee889fe070bbf1ffcf57d9842887f7bdc3570/src/Directory.Build.props#L11

**Comment by AArnott** [comment]
Thanks for noticing. It turns out that the second line you pointed out takes care of it by defining `SPAN_BUILTIN` for `netcoreapp3.1`. But I should remove the line from the csproj since it looks misleading.
