### ISSUE TITLE
PipeReader from ReadOnlySequence<byte>

### ISSUE THREAD

**Issue by Alxandr** [AArnott/Nerdbank.Streams#306]
If you have a byte-array in .NET, you can turn it into a Stream by creating a MemoryStream over it. I'm missing something similar for a `ReadOnlySequence<byte>` and APIs that expect `PipeReader`s (or I have simply not found it). I figured this would be the right library for something like this?

Currently I do `PipeReader.Create(AsStream())`, but going through a stream seems weirdly unneeded, as what you could have is simply a `PipeReader` that returns the entire `ReadOnlySequence` (or what hasn't been consumed of it) every time.

**Comment by AArnott** [comment]
@davidfowl Is this a use case that .NET would want to add directly?

**Comment by davidfowl** [comment]
What APIs are you trying to call?

**Comment by Alxandr** [comment]
I have a `FrameReader` which implemenets `IAsyncEnumerable<Frame>` and accepts a `PipeReader`. It will read and yield `Frame`s. As a logic simplification (and to remove a sync over async bug) we decided today change some of the places we read data to read all the data into memory (`blob.DownloadToStreamAsync(seq.AsStream())`, then deserialize over only in-memory already-downloaded data, so we have something like this:

```csharp
using var seq = new Sequence<byte>();
// here we used to do `OpenStream` and create a `PipeReader` from it.
await blob.DownloadToStreamAsync(seq.AsStream()).ConfigureAwait(false);
var reader = PipeReader.Create(seq.AsReadOnlySequence.ToStream());
await foreach (var frame in reader) {
   // do stuff with message frame
}
```

**Comment by davidfowl** [comment]
Isn't it more efficient to do this:

```C#
var pipe = new Pipe();
await blob.DownloadToStreamAsync(pipe.Writer.AsStream()).ConfigureAwait(false);
await foreach (var frame in FrameReader.Create(pipe.Reader)) {
   // do stuff with message frame
}
```

You can even do it in parallel:

```C#
var pipe = new Pipe();
async Task DoBlobAsync() 
{
    try
    {
        await blob.DownloadToStreamAsync(pipe.Writer.AsStream()).ConfigureAwait(false);
    }
    finally 
    {
        await pipe.Writer.CompleteAsync();
    }
}

var blobTask = DoBlobAsync();
await foreach (var frame in FrameReader.Create(pipe.Reader)) {
   // do stuff with message frame
}
await pipe.Reader.CompleteAsync();
await blobTask;
```

**Comment by Alxandr** [comment]
Probably, yes. I'll take a look over it again on monday and might change to one of these. The reason I started looking into the code at all was due to a thread starvation in production caused by `Stream.Dispose`, so first priority was just to fix that.

That being said, I still feel like there is a component missing here, in that there is no good way to turn already loaded data into a reader. The other reason is probably just that the whole `Stream.Dispose` issue caused me to be more wary of using `Stream`s that I should be (burnt child, fire, and all that).

**Comment by Alxandr** [comment]
Basically, same way as there are legitimate cases for providing a `MemoryStream` to APIs expecting a `Stream` to read from, when the data is available in memory for whatever reason, I would think that you should similarly be able to produce a `PipeReader` from a `ReadOnlySequence<byte>` to present to any API expecting a `PipeReader`. At least to me, that feels like a missing link here.

**Comment by davidfowl** [comment]
Sure I think it's a fine API to add, but I wouldn't recommend it for anything high performance. Make an API request on dotnet/runtime.

**Comment by Alxandr** [comment]
I agree. The reason we decided to just load the entire blobs into memory here is because the largest ones was about 5kb, and we figured that was about what you'd use as a buffer size anyways. And we're using buffer pools for it + this is so far from our performance bottleneck. I'll make an API request on dotnet/runtime once I'm back at work monday and have access to the code in question again :).

**Comment by Alxandr** [comment]
Just a double check, but the following usage of Pipe is sound? I tried to base it on your sample code @davidfowl, but I'm a bit unsure about how exceptions plays into this.

```csharp
        public static async Task DownloadToPipeAsync(
            this CloudBlob blob,
            PipeWriter writer,
            AccessCondition? accessCondition,
            BlobRequestOptions? blobRequestOptions,
            OperationContext? operationContext,
            CancellationToken cancellationToken = default)
        {
            bool errored = false;
            try
            {
                await blob.DownloadToStreamAsync(writer.AsStream(), accessCondition, blobRequestOptions, operationContext, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception e)
            {
                errored = true;
                writer.Complete(e);
            }
            finally
            {
                if (!errored)
                    writer.Complete();
            }
        }

			// later - another method
            var pipe = new Pipe();

            // Start downloading blob to pipe - this will continue in the background
            var dlTask = _blob.DownloadToPipeAsync(pipe.Writer, _lease.ToAccessCondition(), null, null, cancellationToken);

            // prepare reading from pipe
            var frameReader = MessageFrame.GetReader(pipe.Reader, _dispose.Token, _deserializer, cancellationToken);
            await using var enumerator = frameReader.GetAsyncEnumerator(cancellationToken);

            // read items as they become available - desugared foreach (var item in enumerator) { yield return item; } with exception handling
            while (true)
            {
                try
                {
                    if (!await enumerator.MoveNextAsync(cancellationToken).ConfigureAwait(false))
                        break;
                }
                catch (StorageException e) when (e.RequestInformation.ErrorCode == BlobErrorCodeStrings.SourceConditionNotMet
                || e.RequestInformation.ErrorCode == BlobErrorCodeStrings.TargetConditionNotMet)
                {
                    throw new OptimisticConcurrencyException($"Optimistic concurrency error while reading blob. Error code: {e.RequestInformation.ErrorCode}", e);
                }
                catch (StorageException e)
                {
                    throw new Exception($"Reading blob failed with error code: {e.RequestInformation.ErrorCode}", e);
                }

                yield return enumerator.Current;
            }

            // mark that we are done reading from the reader
            await pipe.Reader.CompleteAsync().ConfigureAwait(false);

            // wait for the writer/download to complete (this *should* already have happened normally)
            await dlTask.ConfigureAwait(false);
```

**Comment by davidfowl** [comment]
Looks great you might want to handle errors on the reading side. You need to dispose complete the reading side of things even if there's an exception.

Also use CompleteAsync on both sides

**Comment by Alxandr** [comment]
Btw; in case you're interested; I made the suggestion here: https://github.com/dotnet/runtime/issues/47990
