### ISSUE TITLE
Implement NestedStream.Position

### ISSUE THREAD

**Issue by qmfrederik** [AArnott/Nerdbank.Streams#332]
`NestedStream` is aware of how many bytes of data it has consumed (since it keeps track of the number of bytes which are available for reading).

Therefore, I'd like to request for `NestedStream` to implement the `Position` property.

I can open a PR for this if you agree this is a useful addition.

**Comment by AArnott** [comment]
Per [the docs for `Stream.Position`](https://docs.microsoft.com/en-us/dotnet/api/system.io.stream.position?view=net-5.0#remarks):

> The stream must support seeking to get or set the position. Use the CanSeek property to determine whether the stream supports seeking.

Interestingly though, [the docs for `CanSeek`](https://docs.microsoft.com/en-us/dotnet/api/system.io.stream.canseek?view=net-5.0#remarks) states only that (emphasis added):

> If a class derived from Stream does not support seeking, calls to Length, SetLength, Position, and Seek _may_ throw a NotSupportedException.

Certainly if `CanSeek` were to return `true`, *all* these properties and methods should work. But if it returns `false`, it's less clear. Certainly code should not expect (or at least rely on) `Position` to work when `CanSeek` returns `false`.
