### ISSUE TITLE
Implement NestedStream.Seek (for forward-only seeking)

### ISSUE THREAD

**Issue by qmfrederik** [AArnott/Nerdbank.Streams#333]
It would be awesome if `NestedStream` could implement `Seek` for forward-only seek operations (e.g. `Seek(offset, SeekOrigin.Current)`).

With the current implementation, the only way to skip over irrelevant sections of a `NestedStream` is to `Read(...)` the data into a throw-away buffer, which is kind of wasteful.

**Comment by AArnott** [comment]
> which is kind of wasteful.

That's how we would implement it internally as well (assuming the underlying stream does not support seeking). I suppose we could do better when it _does_ support seeking though. And if that is the case, I see no reason we couldn't support _all_ the seek operations including bidirectional seek, Length, CanSeek, etc.

When the underlying stream does not support seeking, IMO we should not pretend it does by adding a read loop internally. If your goal is to seek forward on a non-seekable stream, that's a general problem that a general extension method could solve.

**Comment by qmfrederik** [comment]
Closed via #334
