### ISSUE TITLE
TraceSource managed memory leak at create channel

### ISSUE THREAD

**Issue by nigma143** [AArnott/Nerdbank.Streams#362]
When creating channels frequently (We do not use channel tracing)
![image](https://user-images.githubusercontent.com/50573226/122684526-7a68dd80-d20e-11eb-913f-0e0ef210d0d5.png)
![Untitled](https://user-images.githubusercontent.com/50573226/122684608-fc590680-d20e-11eb-9480-e9b306845864.png)

**Comment by nigma143** [comment]
objects live up to generation 2, and will live until memory pressure appears

**Comment by nigma143** [comment]
workaround:
```
var noopTraceSource = new TraceSource("noop", SourceLevels.Critical);

var options = new MultiplexingStream.Options
{
   DefaultChannelTraceSourceFactoryWithQualifier = (id, s) => noopTraceSource
};
```

**Comment by AArnott** [comment]
Thanks for calling this out. The behavior of the `MultiplexingStream` is by design. I certainly disagree with the design of `TraceSourc` adding itself to a static collection, but I wouldn't call it a leak since the memory is eventually collected according to the GC rules.
