### ISSUE TITLE
Roadmap for a stable release which includes #334, #346

### ISSUE THREAD

**Issue by qmfrederik** [AArnott/Nerdbank.Streams#369]
We would like to publish a release version of a package which has a dependency on NerdBank.Streams to NuGet.
But, our package currently depends on the features implemented in #334 and #346 (and to a lesser extent, #345).

The only version of NerdBank.Streams which includes these fixes is 2.8.22-alpha (which, by the way, is missing a tag in GitHub 😄). But non-preprelease NuGet packages cannot depend on prerelease NuGet packages, so this is preventing us from publishing our package to NuGet as a released version.

As it stands, I see these options:

1. We copy the relevant parts of NerdBank.Streams to our codebase (doable, but I'd really like to avoid this, if possible)
2. #334, #346 and possibly #345 are backported to the 2.7 branch (happy to open a PR for this)
3. There's a stable release of 2.8 (which I assume is not planned for the immediate future)

So any chance 2 or 3 could happen? Happy to assist where needed.

**Comment by AArnott** [comment]
We can make 3 happen.

**Comment by AArnott** [comment]
And I published the release notes for the last couple of nuget.org releases that were missing. Thanks for calling my attention to that.

**Comment by AArnott** [comment]
Watch for 2.8.46 to show up on nuget.org within the hour.
