### ISSUE TITLE
CI build's code coverage test run is broken

### ISSUE THREAD

**Issue by AArnott** [AArnott/Nerdbank.Streams#39]
If you look at the Azure Pipelines build logs, the code coverage step of the Windows builds is merely a printout of proper usage because the command line we're using is malformed.

**Comment by AArnott** [comment]
It's broken (again).

**Comment by hanabi1224** [comment]
@AArnott  I believe OpenCover does not support DebugType portable, which is required for snupkg tho.  Maybe consider switching to coverlet instead.
