### ISSUE TITLE
Include copy of SequenceReader in netstandard2.0 build.

### ISSUE THREAD

**Issue by tmds** [AArnott/Nerdbank.Streams#433]
`SequenceReader<T>` is only available netstandard2.1+.
That means it is not available for .NET Framework.

Could the netstandard2.0 build of this library include a copy of `SequenceReader<T>`?

See https://github.com/dotnet/standard/issues/1493.

**Comment by AArnott** [comment]
Are you aware this library already has a [`SequenceTextReader`](https://github.com/AArnott/Nerdbank.Streams/blob/main/doc/SequenceTextReader.md)?

We also have an internal [`ReadOnlySequence<byte>` to `Stream` adapter](https://github.com/AArnott/Nerdbank.Streams/blob/main/src/Nerdbank.Streams/ReadOnlySequenceStream.cs), which we could make public if that would be helpful.

I get that neither of these accomplish all that `SequenceReader<T>` can do, and I think copying it into this library is a fine idea. I just wanted to check that you were aware of what's already available.

**Comment by AArnott** [comment]
This will first appear in the 2.9.45-alpha version on nuget.org in a few minutes.

**Comment by tmds** [comment]
Awesome! Thanks!

fyi, the `TextReader` doesn't work for me because my byte stream isn't encoded text.
The adaptor doesn't help me because the `Stream` API is not delivering the interesting things `SequenceReader` provides.
