### ISSUE TITLE
SequenceReader<T> declares members not found in netstandard2.1

### ISSUE THREAD

**Issue by AArnott** [AArnott/Nerdbank.Streams#437]
As @tmds pointed out in https://github.com/AArnott/Nerdbank.Streams/pull/435#issuecomment-1017208167, the `SequenceReader<T>` I copied from came from .NET 7, and thus includes more members than the `netstandard2.1` version that we type forward to, leading to runtime errors.

Specifically, these are the members that should be removed:

- `bool TryReadTo(out ReadOnlySpan<T> span, ReadOnlySpan<T> delimiter, bool advancePastDelimiter = true)`
- `void AdvanceToEnd()`
- `ReadOnlySequence<T> UnreadSequence { get; }`
- `bool TryPeek(long offset, out T value)`

Alternatively, we could only type forward on net5.0 and above (which defines all the above members), but we'd need to see how badly that would impact folks who target netstandard2.1 and reference this library due to type name conflicts.

**Comment by AArnott** [comment]
Ya, just tested and the netstandard2.1 experience is broken at design/compile-time if we leave the type around.

**Comment by tmds** [comment]
Thanks!
