### ISSUE TITLE
Way too many calls to pool rentals when MinimumSpanLength is specified

### ISSUE THREAD

**Issue by rmja** [AArnott/Nerdbank.Streams#532]
The current implementation in Sequence does not return the remaining space in the current buffer allocation when MinimumSpanLength is specified.

According to the documentation of `MinimumSpanLength`:

```
/// Each time <see cref="GetSpan(int)"/> or <see cref="GetMemory(int)"/> is called,
/// previously allocated memory is used if it is large enough to satisfy the length demand.
```

This is however not what currently happens. Instead new memory is allocated for every call to GetSpan and GetMemory().

PR incoming.

**Comment by rmja** [comment]
@AArnott Will this trigger a new patch release? 🙈

**Comment by AArnott** [comment]
Yes: https://github.com/AArnott/Nerdbank.Streams/releases/tag/v2.8.65
