### ISSUE TITLE
Allow non-closing stream for pipes

### ISSUE THREAD

**Issue by fubar-coder** [AArnott/Nerdbank.Streams#67]
# Use case

I have an "interesting" problem, that I have to be able to "enable/disable" an `SslStream` on an open connection. The idea is to wrap an `IDuplexPipe` in a `Stream` which gets passed (if requested) to an `SslStream`. Now, the client should be able to return to a non-encrypted connection - for example to use a different certificate, etc...).

# Possible solution

The ideal solution would be to tell the `PipeStream` to keep the underlying pipes open when `Dispose` gets called. Now I would be able create new streams on the same old pipes.

My workaround is to use the [`RawStream` implementation](https://github.com/aspnet/AspNetCore/blob/a3c8bd16f7c0eaa473364460e0354b2b0cc7fdad/src/Servers/Kestrel/Core/src/Adapter/Internal/RawStream.cs) from the Kestrel project.

**Comment by AArnott** [comment]
I see. So you're using the `IDuplexPipe.AsStream()` extension method today, and this part of the returned `Stream` is getting you down?

https://github.com/AArnott/Nerdbank.Streams/blob/a5d20a18b9887edbe55ce8f34ed0e217f85395c4/src/Nerdbank.Streams/PipeStream.cs#L221-L229

If an `AsStream(bool keepOpen)` overload existed so you could pass `true` in to skip the meat of that Dispose method, would that satisfy your requirement?

**Comment by fubar-coder** [comment]
Yes, that would be perfect.
